data=["vous êtes loin de <LOC> Villers le Lac </LOC>", 
      "Campus de <LOC> Besançon </LOC>", "c'est bien au 100 rue de ",
      "pour l'intervention à <LOC> Villers le Lac </LOC>", 
      "excusez-moi à <LOC> Villers le Lac</LOC>",
      "il est parti à <LOC> Besançon </LOC>",
      "il est à <LOC> Besançon Besançon Morteau </LOC>",
      "le SMUR de <LOC> Pontarlier </LOC> ",
      "le maire de <LOC> New York </LOC>","Monsieur Pasquier Xavier au <LOC> 6 cité comtoise à Mélisey </LOC>",
      "<LOC> Melisez 6 cité comtoise </LOC> c'est une maison un appartement","j'habite <LOC> Lure </LOC>", 
      "d'aller à <LOC> Besançon </LOC>", "vous êtes à <LOC> Lure </LOC> ", "vous êtes à <LOC> Lure </LOC> ",
      "je suis près de entre <LOC> Vesoul </LOC> et <LOC> Besançon </LOC> ", "je suis suivie à <LOC> Besançon </LOC>",
       "je suis arrivé en camion de <LOC> Belfort </LOC>", "c'est dans le <LOC> Doubs </LOC>",
      "c'est le Territoire de <LOC> Belfort </LOC>","à l'hôpital de <LOC> Trévenans </LOC>", "le <LOC> Prieuré </LOC> c'est en ",
      "vous pouvez montez au <LOC> Prieuré </LOC>","je suis à <LOC> Belfort </LOC>",
      "avenue d' <LOC> Altkirch </LOC>", "la rue d' <LOC> Altkirch </LOC>", "à quinze rue <LOC> Emile Schlumberger  </LOC> ", 
      "je suis au <LOC>  quarante-deux avenue </LOC>", 
      "quelle commune <LOC>  Besançon </LOC>",
      "à quelle adresse à <LOC> quinze rue Emile Schlumberger </LOC>"
      "c'est le combien <LOC>  15 rue Emile Schlumberger </LOC>"
      "je vous appellais du <LOC>  Bizot </LOC>",
      "quelle commune <LOC> Montbéliard </LOC>",
      "sur la commune de <LOC>  Dortan </LOC>",
      "vous êtes vers <LOC>  Arc et Senans </LOC>",
      "votre adresse <LOC>  cent huit bis avenue Carnot </LOC> à <LOC> Lure </LOC>",
      "à l'hôpital <LOC> CHU Minjoz </LOC>",
      "c'est la <LOC> Franche-comté </LOC>","c'est à <LOC> Kimvert </LOC> ","la commune de <LOC> Dortan </LOC>",
      "je vous appellais du <LOC> Bizot </LOC> ", "madame sur le <LOC> Bizot </LOC>", "son prénom <LOC> Léanne <LOC>",
      "la commune du <LOC> Bizot </LOC>",
      "docteur <LOC> Chevrolet </LOC>","quelle adresse à <LOC> Fougerolles cent quatre Blanzey </LOC>",
      "maman de Capucine ", "à quinze rue <LOC> Emile Schlumberger </LOC> "
      ]